ALTER TABLE "HeroSlide" ADD COLUMN "heading" TEXT NOT NULL DEFAULT '';
ALTER TABLE "HeroSlide" ADD COLUMN "subheading" TEXT NOT NULL DEFAULT '';
ALTER TABLE "HeroSlide" ADD COLUMN "description" TEXT NOT NULL DEFAULT '';
ALTER TABLE "HeroSlide" ADD COLUMN "ctaText" TEXT NOT NULL DEFAULT '';
ALTER TABLE "HeroSlide" ADD COLUMN "ctaLink" TEXT NOT NULL DEFAULT '';
